name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, latest]
      fail-fast: false

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'db_migrate_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'super123' # Required if "mysql user" is empty, default is empty. The root superuser password
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i -g npm@9.x.x
      - run: npm ci
      - run: npm i db-migrate@beta
      - run: cp test/db.config.ci test/db.config.json
      - run: npm test
